README.md
=> Maintainers Name Fix

package.json
Right now tests fail because the wrong version of webpack is being installed
=> fix webpack version

src/index.js
=> only load CSS once

README.md
This PR fixes a grammatical issue.
=> Chore: Fix typo in README

README.md
=> docs(readme): fix simple example

test/TestMemoryFS.test.js
=> [WIP] ci: fix test

README.md
=> Uglify -> Terser

package-lock.json, package.json
Downgrading normalize-url to close issues opened around ES5 support required in IE
Internet Explorer is awesome...
fix #385
=> fix: downgrading normalize-url

package.json
=> chore: add test manual script

src/index.js
=> chore: fix typo

src/loader.js
=> fix: context for dependencies

jest.config.js, setupTest.js
=> ci: improve timeout

src/CssDependencyTemplate.js, src/CssModule.js, src/CssModuleFactory.js, src/index.js, src/loader.js, src/utils.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/common.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/entry1.js, test/cases/dependOn/expected/webpack-5/common.js, test/cases/dependOn/expected/webpack-5/entry1.js
=> Refactor code

package-lock.json, test/TestCache.test.js
improve test for caching
No
No
=> test: improve

.prettierrc.js, babel.config.js, lint-staged.config.js
update config for babel and lint-staged
No, because we already drop old node versions
No
=> chore(tool): fix

.github/workflows/nodejs.yml
=> ci: update

README.md, package-lock.json, src/CssLoadingRuntimeModule.js, src/index.js, src/plugin-options.json, test/__snapshots__/attributes-option.test.js.snap, test/__snapshots__/validate-plugin-options.test.js.snap, test/attributes-option.test.js, test/cases/hmr/expected/webpack-5/main.js, test/cases/insert-function/expected/webpack-4/main.js, test/cases/insert-function/expected/webpack-5/main.js, test/cases/insert-string/expected/webpack-4/main.js, test/cases/insert-string/expected/webpack-5/main.js, test/cases/insert-undefined/expected/webpack-4/main.js, test/cases/insert-undefined/expected/webpack-5/main.js, test/fixtures/attributes.js, test/validate-plugin-options.test.js
=> Feat added attributes option

src/CssLoadingRuntimeModule.js, src/index.js, test/cases/hmr/expected/webpack-5/main.js, test/cases/insert-function/expected/webpack-4/main.js, test/cases/insert-function/expected/webpack-5/main.js, test/cases/insert-string/expected/webpack-4/main.js, test/cases/insert-string/expected/webpack-5/main.js, test/cases/insert-undefined/expected/webpack-4/main.js, test/cases/insert-undefined/expected/webpack-5/main.js
=> fix: onerror request

src/index.js, src/loader.js
=> Fix: improved webpack version check

src/index.js, src/loader.js
=> fix: serializing big strings

README.md
Fix type: missing comma after a commented line in code example
NA
=> Typo in README code example

src/index.js, test/TestCache.test.js
fixes https://github.com/webpack/webpack/issues/12489
No
No
=> fix: yarn pnp compatibility

README.md
=> docs: improve split chunks

package.json
For watching with the `webpack-cli@4` need used `webpack serve` command
No
No
=> Chore: updated test:manual command

test/TestCases.test.js, test/cases/auxiliaryAssets/test.filter.js
=> test: refactor

package-lock.json, package.json, src/index.js, src/loader.js, src/utils.js, test/TestCache.test.js
update deps + small refactor (avoid mix logic)
No
No
=> refactor: code

README.md
Add an example for the new `experimentalUseImportModule` option.
=> docs: add example for experimentalUseImportModule

package-lock.json, package.json, src/loader.js, src/utils.js
=> Refactor reduce deps

package-lock.json, package.json, src/loader-options.json, src/plugin-options.json, test/__snapshots__/validate-loader-options.test.js.snap, test/__snapshots__/validate-plugin-options.test.js.snap
add `link` and `description`
None
No
=> feat: add `link` and `description` for options

package-lock.json, package.json, test/cases/hmr/expected/main.js
=> chore(deps): update

package-lock.json, package.json, test/manual/webpack.config.js
update dev server and manual tests
No
No
=> chore: update dev server and manual tests

package-lock.json, test/cases/js-hash/expected/webpack-5-importModule/style.43ad9cd468159815bd3e.1.css, test/cases/js-hash/expected/webpack-5-importModule/style.bf54e341e5d75d24c387.2.css, test/cases/js-hash/expected/webpack-5-importModule/style.ff389914a5cf993f5135.1.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/a.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/a.js, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/b.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/b.js, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/common.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/components/comp1.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/components/comp1.js, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/components/comp2.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/components/comp2.js, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/expected/comp1.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/expected/comp2.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/expected/styles_a.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/expected/styles_b.css, test/cases/split-chunks-based-on-entry-with-common-in-each-chunk/webpack.config.js
example for #804 where common chunk in each chunk
No
No
=> test: more

test/cases/at-charset/a.css, test/cases/at-charset/aa.css, test/cases/at-charset/ab.css, test/cases/at-charset/ac.css, test/cases/at-charset/ad.css, test/cases/at-charset/ae.css, test/cases/at-charset/b.css, test/cases/at-charset/ba.css, test/cases/at-charset/bb.css, test/cases/at-charset/expected/main.css, test/cases/at-charset/index.js, test/cases/at-charset/webpack.config.js
add bad test case for `@charset`
No
we need to fix it in `css-loader`
=> test: `@charset`

README.md, src/plugin-options.json, test/__snapshots__/validate-plugin-options.test.js.snap
=> docs: clarify

README.md
=> docs: improve readme for source maps

test/cases/split-chunks-no-vendor/expected/bundle.css, test/cases/split-chunks-no-vendor/index.js, test/cases/split-chunks-no-vendor/node_modules/bootstrap/bootstrap.css, test/cases/split-chunks-no-vendor/node_modules/other-css/other.css, test/cases/split-chunks-no-vendor/node_modules/package/index.js, test/cases/split-chunks-no-vendor/style.css, test/cases/split-chunks-no-vendor/webpack.config.js
=> test: add example

src/loader.js, test/cases/export-only-locals-and-es-named-export/expected/main.js, test/cases/export-only-locals-and-es-named-export/index.js, test/cases/export-only-locals-and-es-named-export/style.css, test/cases/export-only-locals-and-es-named-export/webpack.config.js, test/cases/export-only-locals-commonjs/expected/main.js, test/cases/export-only-locals-commonjs/index.js, test/cases/export-only-locals-commonjs/style.css, test/cases/export-only-locals-commonjs/webpack.config.js, test/cases/export-only-locals/expected/main.js, test/cases/export-only-locals/index.js, test/cases/export-only-locals/style.css, test/cases/export-only-locals/webpack.config.js
=> fix: crash with the `exportLocalsConvention` option

src/utils.js
=> fix: context bug

package-lock.json, package.json, test/cases/publicpath-function-2/expected/webpack-5/nested/again/style.css, test/cases/publicpath-function-2/expected/webpack-5/nested/style.css
=> chore(dependencies): update webpack version

.github/workflows/nodejs.yml
=> ci: add node-18 workflow

README.md
=> chore(docs): Update typo in example

src/index.js, test/cases/issue-css-loader-1503-1/dark.css, test/cases/issue-css-loader-1503-1/expected/dark.css, test/cases/issue-css-loader-1503-1/expected/index.css, test/cases/issue-css-loader-1503-1/index.css, test/cases/issue-css-loader-1503-1/webpack.config.js, test/cases/issue-css-loader-1503-2/dark.css, test/cases/issue-css-loader-1503-2/expected/dark.css, test/cases/issue-css-loader-1503-2/expected/index.css, test/cases/issue-css-loader-1503-2/index.css, test/cases/issue-css-loader-1503-2/webpack.config.js, test/cases/issue-css-loader-1503/dark.css, test/cases/issue-css-loader-1503/expected/dark.css, test/cases/issue-css-loader-1503/expected/index.css, test/cases/issue-css-loader-1503/index.css, test/cases/issue-css-loader-1503/webpack.config.js
fixes https://github.com/webpack-contrib/css-loader/issues/1503
No
No
=> fix: module identifier, don't merge modules with different media/suppors/layer

src/index.js
Improve identifier to avoid `undefied` + better output
No
No
=> fix: readable identifier

.github/workflows/nodejs.yml
Use `npm ci` to install dependencies
No
No
=> ci: use `npm ci` to install dependencies

src/index.js
Giving css with at-rule-import
```css
@import "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" screen and (min-width:640px);
@import "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"; 
div{
color:red;
font-size:14px
}
```
```css
@import "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" screen and (min-width:640px)@import "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"; 
div{
color:red;
font-size:14px
}
```
After bugfix
```css
@import "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" screen and (min-width:640px);
@import "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"; 
div{
color:red;
font-size:14px
}
```
=> add ';'to module.media

.github/workflows/nodejs.yml
fixes https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1060
No
No
=> ci: bump github actions

README.md
=> fix: README.md namedExport example fix

README.md
update github syntax of note and warning
No
No
=> docs: update github syntax of note and warning
