webpack-contrib/mini-css-extract-plugin

src/loader.js
The handling was there, but the property it tried to access was being clobbered by the .map's result.
=> fix(loader): Correctly preserve CSS module locals

src/index.js
Right now all generated URLs end up being top level URLs.
Fixes https://github.com/webpack-contrib/mini-css-extract-plugin/issues/2
=> fix(index): Use the runtime publicPath when generating the href

src/loader.js
The loader was using deprecated `Tapable` APIs.
=> Remove deprecated calls to Tapable

src/index.js, test/cases/split-chunks/expected/main.css, test/cases/split-chunks/expected/vendors~main.css, test/cases/split-chunks/index.js, test/cases/split-chunks/node_modules/bootstrap.css, test/cases/split-chunks/style.css, test/cases/split-chunks/webpack.config.js
=> fix splitChunks support

src/loader.js, test/cases/composes-async/async-1.css, test/cases/composes-async/async-2.css, test/cases/composes-async/expected/1.css, test/cases/composes-async/expected/3.css, test/cases/composes-async/index.js, test/cases/composes-async/webpack.config.js
add test case how css deduplication works (fixes #5)
=> Add ident to loaders passed to child compilation

README.md
Following [discussions on the issues](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/52), this PR aims at documenting the common use-case of extracting all CSS in one file, similar to what https://github.com/webpack-contrib/extract-text-webpack-plugin does.
Tested in a small project there: https://github.com/Akkenar/CSS-Single-File-Example
=> Add documentation in README.md about how to extract all CSS in one file

README.md
- Fixes #24 
Add a note and example about minimizing CSS output in Webpack 4
=> docs(README): add information about minimization

package.json, src/index.js, test/manual/webpack.config.js, yarn.lock
This does NOT include HMR support.
It makes incremental builds possible but doesn't integrate with HMR. So for HMR, CSS will not reload.
=> support incremental build

README.md
As discussed with @evilebottnawi in #9, here is a PR adding an advanced example in the docs to avoid confusion and problems with the use of this plugin and the `style-loader`, especially when one wants to have HMR in `development` and its styles extracted for `production` builds.
=> Add an advanced configuration example in README

README.md
**what**
Modified docs to show an example of exporting CSS based on entry. 
**why**
Useful for SSR and people who want to use dynamically loaded routes, but keep CSS bundled based on entry.
=> Add CSS extract based on entry

src/index.js, src/loader.js
Use const instead of repeat literal strings.
None.
=> refactor: replace literal plugin name in strings with const

README.md
Use a capturing group to match only exactly `.sass`, `.scss`, and `.css`.
=> Do not match .ass

README.md
Move the _Long Term Caching_ feature outside of the _Maintainers_ section so it's easier to see.
This minor change improves the legibility of the README.
N/A
=> docs(readme): move long term caching guide from errant section

.babelrc
Babel should have Node target version set to minimal required version declared in `package.json`.
It seems like `.babelrc` has been missed during #82 refactor.
=> build(babel): use same node version as declared in package.json

src/index.js, test/cases/split-chunks-single/a.css, test/cases/split-chunks-single/b.css, test/cases/split-chunks-single/c.css, test/cases/split-chunks-single/chunk1.js, test/cases/split-chunks-single/chunk2.js, test/cases/split-chunks-single/d.css, test/cases/split-chunks-single/e1.css, test/cases/split-chunks-single/e2.css, test/cases/split-chunks-single/entry1.js, test/cases/split-chunks-single/entry2.js, test/cases/split-chunks-single/expected/styles.css, test/cases/split-chunks-single/f.css, test/cases/split-chunks-single/g.css, test/cases/split-chunks-single/h.css, test/cases/split-chunks-single/style.css, test/cases/split-chunks-single/webpack.config.js
see #242
Order of modules is incorrect/undefined when merging multiple chunk groups into a single chunk.
This PR also emits a warning when order is conflicting between chunk groups.
bugfix
=> fix(order): use correct order when multiple chunk groups are merged

src/index.js, src/loader.js
=> refactor: rename `NS` to `MODULE_TYPE` and use a static value

src/index.js, src/loader.js, test/TestMemoryFS.test.js
Looks like `mini-css-extract-plugin` when collecting sources it's replacing module dependencies
with new `CssDependency` as assets are loaded before. IMHO we can collect and add it back to updated module. 
Use-case for this is when using `hard-source-plugin` and reading from cache can't find asset 
https://github.com/mzgoddard/hard-source-webpack-plugin/issues/367
No breaking changes, all current test's are passing
=> fix(loader): pass `emitFile` to the child compilation (`loaderContext.emitFile`)

README.md
Added short note about media-query-splitting-plugin
=> docs(readme): add `media-query-splitting-plugin` (Media Query Plugin)

src/index.js, test/manual/index.html, test/manual/src/crossorigin.css, test/manual/src/crossorigin.js, test/manual/src/index.js, test/manual/webpack.config.js
#312 
Reference [code](https://github.com/webpack/webpack/blob/9b97f3aeb124776731b9830c4964f496a3cdfed8/lib/web/JsonpMainTemplatePlugin.js#L163-L171). We could reuse Webpack [output options](https://webpack.js.org/configuration/output/#output-crossoriginloading).
=> feat: add crossOriginLoading option support

src/index.js
Add error code to chunk load failure https://github.com/webpack-contrib/mini-css-extract-plugin/issues/346
=> feature: added error code to chunk load Error

package-lock.json, src/hmr/hotModuleReplacement.js
No not try and reload non-URL based `<link>` tags
example: `<link rel="shortcut icon" href="data:;base64,=">`
fixs #377
=> fix: do not attempt to reload base64 encoded urls

package-lock.json, src/index.js
Currently `filename` option is checked 3 times for the existence of 3 different strings, this PR replaces the 3 `filename.includes(x)` with a single regular expression test for a [small boost](http://jsben.ch/vpOJX) in performance.
None
=> perf: match filename placeholders with regular expression

package-lock.json, src/index.js, test/cases/default-options/expected/main.css, test/cases/default-options/index.js, test/cases/default-options/style.css, test/cases/default-options/webpack.config.js
Developers using MiniCssExtractPlugin without options will receive an error "cannot read property filename of undefined". This PR fixes that error and enables instantiating MiniCssExtractPlugin without options ie. 
```javascript
plugins: [
new MiniCssExtractPlugin(),
],
```
none
=> fix(options): enable using plugin without defining options

babel.config.js, src/hmr/hotModuleReplacement.js
use babel for client hmr code
No
No
=> refactor: use babel for compiling client code

src/hmr/hotModuleReplacement.js
href can be avoided (non standard sutiation)
No
No
=> fix: hmr do not crash on link without href

src/hmr/hotModuleReplacement.js, test/HMR.test.js, test/__snapshots__/HMR.test.js.snap
=> fix: hmr reload with invalid link url

README.md, package-lock.json, src/index.js, test/IgnoreOrder.test.js, test/cases/ignoreOrder/e1.css, test/cases/ignoreOrder/e2.css, test/cases/ignoreOrder/expected/styles.css, test/cases/ignoreOrder/index.js, test/cases/ignoreOrder/index2.js, test/cases/ignoreOrder/webpack.config.js, test/cases/ignoreOrderFalse/e1.css, test/cases/ignoreOrderFalse/e2.css, test/cases/ignoreOrderFalse/expected/styles.css, test/cases/ignoreOrderFalse/index.js, test/cases/ignoreOrderFalse/index2.js, test/cases/ignoreOrderFalse/webpack.config.js, test/ignoreOrder-option.test.js
Picking up the torch where https://github.com/webpack-contrib/mini-css-extract-plugin/pull/366 left off and making the changes suggested by @evilebottnawi 
Also addresses #362
Borrowing @hedgepigdaniel 's description:
As has been pointed out in #250:
* Sorting all imports (not just in files but in tree traversal import order is difficult to do in a large project, and impossible if there are async chunks with CSS.
* Consistent use of scoping or naming conventions in CSS makes the order of CSS import irrelevant, and this is a much more manageable strategy for a large project as @jsg2021 said in #250 (comment)
* Using stats.warningFilter as recommended by @sokra in #250 (comment) or webpack-filter-warnings-plugin does not work consistently. It's much better to avoid …
=> feat: Add ignoreOrder flag

src/index.js, test/cases/moduleFilenameMutableFilename/expected/mutated.css, test/cases/moduleFilenameMutableFilename/index.js, test/cases/moduleFilenameMutableFilename/style.css, test/cases/moduleFilenameMutableFilename/webpack.config.js
A minor update from 0.6.0 to 0.7.0 broke my webpacker configuration. :(
In https://github.com/webpack-contrib/mini-css-extract-plugin/commit/13e9cbf3fb58f69e931c564ca4360cef439512c4 (https://github.com/webpack-contrib/mini-css-extract-plugin/pull/381) the `moduleFilename` function was added. This change broke webpacker configurations that set a non-default `filename` option.
To explain further, if you view the [webpacker plugins docs](https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins), options can be mutated after construction.
Excerpt from docs:
```
// Get a pre-configured plugin
const manifestPlugin = environment.plugins.get('Manifest')
manifestPlugin.options.writeToFileEmit = false
```
So, previously, I could set a filename like so:
``` …
```
=> fix(options): use filename mutated after instantiation

package-lock.json, src/CssDependency.js, src/index.js, src/loader.js
I want to make the code of the plugin a bit easier to understand and debug by removing unnecessary hidden connection between `index.js` and `loader.js` and changing variables and functions names to a bit more clear variants.
=> Refactor loader's code

package-lock.json, src/index.js, test/TestCases.test.js, test/cases/ignoreOrderFalse/e3.css, test/cases/ignoreOrderFalse/expected/styles.css, test/cases/ignoreOrderFalse/index3.js, test/cases/ignoreOrderFalse/warnings.js, test/cases/ignoreOrderFalse/webpack.config.js
Many issues have been raised related to the warning of mini-css-extract-plugin regarding the conflict of order (example: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/382 and https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250). For me, the warning is a bit confusing as it does not provide enough details of why it goes wrong.
In this PR, I am trying to provide more info about:
+ what module has been added to the css asset;
+ why adding this module creates warnings;
+ which chunks you should probably take a look into.
In current version, running the unit test will generate the following warning:
```
WARNING in chunk styles [mini-css-extract-plugin]
Conflicting order between:
* css xxx/css-loader/dist/cjs.js!./e1.css
* css …
```
=> feat: improve warning of conflict order

src/index.js, test/cases/ignoreOrderFalseWithoutGoodChunks/e1.css, test/cases/ignoreOrderFalseWithoutGoodChunks/e2.css, test/cases/ignoreOrderFalseWithoutGoodChunks/e3.css, test/cases/ignoreOrderFalseWithoutGoodChunks/e4.css, test/cases/ignoreOrderFalseWithoutGoodChunks/expected/styles.css, test/cases/ignoreOrderFalseWithoutGoodChunks/index.js, test/cases/ignoreOrderFalseWithoutGoodChunks/index2.js, test/cases/ignoreOrderFalseWithoutGoodChunks/index3.js, test/cases/ignoreOrderFalseWithoutGoodChunks/index4.js, test/cases/ignoreOrderFalseWithoutGoodChunks/warnings.js, test/cases/ignoreOrderFalseWithoutGoodChunks/webpack.config.js
This is a minor fix of https://github.com/webpack-contrib/mini-css-extract-plugin/pull/465.
There are chances that a module is introduced with failed dependencies, and there is no chunk fulfill the desired order (This happens when all available chunks have bad dependencies and plugin has to choose the one with less failed). I have create a new unit test for this situation. Without the fix, it will output something like:
`   - while fulfilling desired order of chunk group(s) undefined`
while after this fix, this line will be simply removed.
The test case can be simplified as following:
+ chunk1: css1
+ chunk2: css2, css1
+ chunk3: css3, css4, css2
+ chunk4: css4, css2, css3
Plugin will choose `css1` in first step, with failed dependency `css2`; but there is no chunk …
=> fix: only output when any chunk is fulfilled

README.md, src/loader.js, src/options.json, test/cases/commonjs-module-syntax/expected/main.css, test/cases/commonjs-module-syntax/index.js, test/cases/commonjs-module-syntax/style.css, test/cases/commonjs-module-syntax/webpack.config.js, test/cases/es-module-syntax/expected/main.css, test/cases/es-module-syntax/index.js, test/cases/es-module-syntax/style.css, test/cases/es-module-syntax/webpack.config.js
=> feat: new `esModule` option

test/cases/no-source-map/expected/main.css, test/cases/no-source-map/index.js, test/cases/no-source-map/style.css, test/cases/no-source-map/webpack.config.js
fixes #285
No
To disable source maps generation you need set `sourceMap: false` for `css-loader` and set `devtools: false`, we will try to fix and simplify it in webpack@5
=> test: fix invalid test and source map test

src/loader-options.json, test/__snapshots__/validate-loader-options.test.js.snap, test/validate-loader-options.test.js
=> refactor: more options for schema

src/loader.js, test/enforce-esm.test.js, test/fixtures/esm.js, test/helpers/getCompiler.js, test/helpers/index.js, test/helpers/source.js
Enforce esm for empty module, so webpack can make some optimizations.
No
related issue https://github.com/webpack/webpack/issues/10889
=> fix: enforce esm

src/index.js, test/cases/dependOn-multiple-files-per-entry/entryA.js, test/cases/dependOn-multiple-files-per-entry/entryB.js, test/cases/dependOn-multiple-files-per-entry/entryC.js, test/cases/dependOn-multiple-files-per-entry/entryD.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/common.css, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/common.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/entry1.css, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/entry1.js, test/cases/dependOn-multiple-files-per-entry/styleA.css, test/cases/dependOn-multiple-files-per-entry/styleB.css, test/cases/dependOn-multiple-files-per-entry/styleC.css, test/cases/dependOn-multiple-files-per-entry/styleD.css, test/cases/dependOn-multiple-files-per-entry/webpack.config.js, test/cases/dependOn/entryA.js, test/cases/dependOn/entryB.js, test/cases/dependOn/expected/webpack-5/common.css, test/cases/dependOn/expected/webpack-5/common.js, test/cases/dependOn/expected/webpack-5/entry1.css, test/cases/dependOn/expected/webpack-5/entry1.js, test/cases/dependOn/styleA.css, test/cases/dependOn/styleB.css, test/cases/dependOn/webpack.config.js, test/cases/hmr/expected/webpack-5/main.js
A missing semicolon after the closing `}` when defining
`installedCssChunks` causes the object `{ "common": 0}` to be
incorrectly interpreted as a function
fixes #560
The compiled javascript pack is generated by Webpack v5 as follows:
```
...
/******/  // object to store loaded CSS chunks
/******/  var installedCssChunks = {
/******/    "common": 0
/******/  }/* webpack/runtime/jsonp chunk loading */
/******/  (() => {
/******/    // object to store loaded and loading chunks
/******/    // undefined = chunk not loaded, null = chunk preloaded/prefetched
/******/    // Promise = chunk loading, 0 = chunk loaded
/******/    var installedChunks = {
/******/      "common": 0
/******/    };
....
```
n/a
=> fix: add semicolon to avoid `Uncaught TypeError` on Webpack v5

.editorconfig, test/cases/es-module-concatenation/a.css, test/cases/es-module-concatenation/b.css, test/cases/es-module-concatenation/c.css, test/cases/es-module-concatenation/expected/webpack-4/main.css, test/cases/es-module-concatenation/expected/webpack-4/main.js, test/cases/es-module-concatenation/expected/webpack-5/main.css, test/cases/es-module-concatenation/expected/webpack-5/main.js, test/cases/es-module-concatenation/index.js, test/cases/es-module-concatenation/webpack.config.js, test/enforce-esm.test.js
=> test: add some es-modules concatenation cases

src/index.js, src/loader.js, test/cases/moduleFilename/webpack.config.js, test/cases/moduleFilenameMutableFilename/webpack.config.js
=> Remove deprecated hooks

src/loader.js, test/TestCases.test.js
=> refactor: code

src/loader.js, test/TestCache.test.js
test cache for webpack@5
No
No
=> test: cache

src/CssDependency.js, src/CssModule.js
=> fix: fix Cannot find module 'mini-css-extract-plugin/src/CssDependency'

README.md, src/CssLoadingRuntimeModule.js, src/CssModule.js, src/index.js, src/loader.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/common.js, test/cases/dependOn/expected/webpack-5/common.js, test/cases/hmr/expected/webpack-5/main.js, test/cases/hmr/webpack.config.js, test/enforce-esm.test.js, test/manual/index.html, test/manual/src/index.js, test/manual/src/lazy.module.css, test/manual/webpack.config.js
better support for webpack 5
none, as webpack 5 support is experimental,
but it's notable that you must no longer pass the `hmr` option when using webpack 5, as this is automatically inferred as it's using the webpack 5 HMR integration
=> better support for webpack 5

src/CssDependency.js, test/TestCases.test.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/common.js, test/cases/dependOn-multiple-files-per-entry/expected/webpack-5/entry1.js, test/cases/dependOn/expected/webpack-5/common.js, test/cases/dependOn/expected/webpack-5/entry1.js, test/cases/es-module-concatenation-modules/a.css, test/cases/es-module-concatenation-modules/b.css, test/cases/es-module-concatenation-modules/c.css, test/cases/es-module-concatenation-modules/expected/webpack-4/main.css, test/cases/es-module-concatenation-modules/expected/webpack-4/main.js, test/cases/es-module-concatenation-modules/expected/webpack-5/main.css, test/cases/es-module-concatenation-modules/expected/webpack-5/main.js, test/cases/es-module-concatenation-modules/index.js, test/cases/es-module-concatenation-modules/webpack.config.js, test/cases/hmr/expected/webpack-5/main.js, test/cases/split-chunks-all/expected/webpack-5/2.js, test/enforce-esm.test.js
mini-css leaves empty "// extract by ..." js modules in the bundle. They are unnecessary.
webpack 5 will analyse the source code as side-effect-free, but as it contains a custom dependency (`CssDependency`), this dependency also need to opt-in into being side-effect-free. But actual it's not completely side-effect-free as it points to CssModules that need to be included in the bundle. So this PR opts in into a "transitive only" side-effects mode, which allows to drop the js module but keeps the dependencies in the bundle.
None
=> feat(webpack-5): opt-in to transitive only side effects

README.md
Improved readme
Fixes #403 
Fixes #259 
No
No
=> Docs: improved readme

README.md
It's a description as I see, so there's no need to add a link? And it's causing the CI failure of webpack.js.org repository https://travis-ci.org/github/webpack/webpack.js.org/jobs/734298251#L860
=> docs: clean unused link in readme

README.md
=> Docs: fix ambiguous docs

src/loader-options.json, test/__snapshots__/validate-loader-options.test.js.snap, test/validate-loader-options.test.js
Removed unused `hmr` option from loader validate options
No
No
=> fix: removed unused `hmr` option

README.md, test/cases/split-chunks-recursiveIssuer/a.css, test/cases/split-chunks-recursiveIssuer/a.js, test/cases/split-chunks-recursiveIssuer/b.css, test/cases/split-chunks-recursiveIssuer/b.js, test/cases/split-chunks-recursiveIssuer/components/comp1.css, test/cases/split-chunks-recursiveIssuer/components/comp1.js, test/cases/split-chunks-recursiveIssuer/components/comp2.css, test/cases/split-chunks-recursiveIssuer/components/comp2.js, test/cases/split-chunks-recursiveIssuer/expected/styles_a.css, test/cases/split-chunks-recursiveIssuer/expected/styles_b.css, test/cases/split-chunks-recursiveIssuer/webpack.config.js
=> docs: update splitChunks info

src/hmr/hotModuleReplacement.js, test/HMR.test.js, test/__snapshots__/HMR.test.js.snap, test/cases/hmr/expected/webpack-4/main.js, test/cases/hmr/expected/webpack-5/main.js
=> fix: error when reloading async chunk

src/index.js, src/loader.js
=> fix: compatibility with webpack@4 and webpack@5 for monorepos

README.md, src/CssLoadingRuntimeModule.js, src/index.js, src/plugin-options.json, test/__snapshots__/linkTag-option.test.js.snap, test/__snapshots__/validate-plugin-options.test.js.snap, test/cases/hmr/expected/webpack-5/main.js, test/cases/insert-undefined/expected/webpack-4/main.js, test/cases/insert-undefined/expected/webpack-5/main.js, test/linkTag-option.test.js, test/validate-plugin-options.test.js
Fixes #328 
`document.head` doesn't work in IE8.
No
=> feat: linkType option

src/CssLoadingRuntimeModule.js, src/index.js, test/cases/hmr/expected/webpack-5/main.js, test/cases/insert-function/expected/webpack-4/main.js, test/cases/insert-function/expected/webpack-5/main.js, test/cases/insert-string/expected/webpack-4/main.js, test/cases/insert-string/expected/webpack-5/main.js, test/cases/insert-undefined/expected/webpack-4/main.js, test/cases/insert-undefined/expected/webpack-5/main.js
=> fix: onerror mem leak

src/loader-options.json, src/plugin-options.json, test/__snapshots__/validate-loader-options.test.js.snap, test/__snapshots__/validate-plugin-options.test.js.snap, test/cases/js-hash/webpack.config.js, test/validate-loader-options.test.js, test/validate-plugin-options.test.js
fix schema
Potential yes, but we should force it because a lot of developers do mistakes
No
=> fix: schema

package-lock.json, package.json, src/index.js, src/loader.js, test/TestCases.test.js, test/cases/serializingBigStrings/webpack.config.js
=> fix: serializing big strings in sourceMap

src/hmr/hotModuleReplacement.js, test/HMR.test.js, test/cases/hmr/expected/webpack-4/main.js, test/cases/hmr/expected/webpack-5/main.js
fixes #683
No
For error we should do the same
=> fix: hmr runtime on preloaded stylesheet link

src/index.js, test/cases/hmr/expected/webpack-5/main.js, test/cases/hmr/webpack.config.js, test/cases/insert-function/expected/webpack-5/main.js, test/cases/insert-string/expected/webpack-5/main.js, test/cases/insert-undefined/expected/webpack-5/main.js, test/cases/runtime/expected/webpack-5/runtime~main.js
=> fix: bloated runtime

src/index.js, test/cases/hmr/expected/webpack-5/main.js
I'm using this plugin on an app running on some old webkit browsers (~Safari 7). After updating to webpack 5, I get  the following error when running in development mode.
```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
```
All the surrounding template code is using var, this one must have been missed.
None
None
=> fix: replace const with var to avoid strict mode errors

src/loader.js, test/cases/es-module-concatenation-modules/expected/webpack-4/main.js, test/cases/es-module-concatenation-modules/expected/webpack-5-importModule/main.js, test/cases/es-module-concatenation-modules/expected/webpack-5/main.js, test/cases/es-named-export-output-module/expected/main.js, test/cases/es-named-export/expected/webpack-4/main.js, test/cases/es-named-export/expected/webpack-5-importModule/main.js, test/cases/es-named-export/expected/webpack-5/main.js
=> fix: compatibility with named export and es5

README.md
I believe the current image url is broken:
=> docs: fix the broken image url

README.md, src/loader-options.json, src/loader.js, test/__snapshots__/validate-loader-options.test.js.snap.webpack4, test/__snapshots__/validate-loader-options.test.js.snap.webpack5, test/cases/es-module-concatenation-modules/webpack.config.js, test/cases/es-named-export-output-module/webpack.config.js, test/cases/es-named-export/webpack.config.js, test/validate-loader-options.test.js
Removed `modules` and `modules.namedExport` option in favor `modules.namedExport` option in [`css-loader`](https://github.com/webpack-contrib/css-loader)
Yes
No
=> refactor: removed modules.namedExport option

package.json
- [] **bugfix**
fix engines filed (we already drop Node.js 10)
Yes, but it was done in other PR
No
=> fix: engines field

test/cases/asset-modules/test.filter.js, test/cases/chunkFilename-as-function/webpack.config.js, test/cases/chunkFilename-fullhash/test.filter.js, test/cases/content-entries-with-same-import/test.filter.js, test/cases/dependOn-multiple-files-per-entry/test.filter.js, test/cases/dependOn/test.filter.js, test/cases/es-named-export-output-module/test.filter.js, test/cases/output-iife/test.filter.js, test/cases/output-module/test.filter.js, test/cases/simple-css-modules-mode-local-output-module/test.filter.js, test/cases/split-chunks-recursiveIssuer/webpack.config.js
remove outdated filters for webpack v4
No
No
=> test: clean up

src/index.js, test/pathinfo.test.js
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/775
=> feat: add pathinfo

.github/workflows/nodejs.yml, test/TestCases.test.js, test/cases/auxiliary-assets/test.filter.js, test/helpers/yn.js
use `y/n` logic for env variables, in future we want to use `loaderContext.importModule` API by default when it is available for perf reasons, let's prepare our tests for this
No
No
=> ci: refactor

README.md, src/index.js, src/plugin-options.json, test/__snapshots__/noRuntime-option.test.js.snap, test/__snapshots__/validate-plugin-options.test.js.snap, test/noRuntime-option.test.js
As seen here https://github.com/webpack-contrib/css-loader/issues/1362 and here https://github.com/webpack-contrib/mini-css-extract-plugin/issues/711 i've added a `noRuntime` option to avoid the runtime generation. Assets are still extracted and can be used for a custom loading methods.
Another PR (https://github.com/webpack-contrib/mini-css-extract-plugin/pull/807) tried to do something similar but does others things and will need a rebase. In comparaison i'm using a more minimal approach and add unit tests that shown that : 
- link tags are not generated when noRuntime is true
- runtime is also [not generated](https://github.com/webpack-contrib/mini-css-extract-plugin/pull/831/files#diff-37fbbb992e4d879cdbc7890d5ebbdf4041b5a63b6f09f8a0e3cdfa74432ecc38R96 ) in this …
=> feat: add a noRuntime option

src/index.js, src/loader.js, test/TestCache.test.js, test/cases/at-import-layer/expected/main.css, test/cases/at-import-layer/import-with-layer-and-supports-and-media.css, test/cases/at-import-layer/import-with-layer.css, test/cases/at-import-layer/index.js, test/cases/at-import-layer/style.css, test/cases/at-import-layer/test.css, test/cases/at-import-layer/unnamed-layer.css, test/cases/at-import-layer/webpack.config.js, test/cases/at-import-layer/zzz.css, test/cases/at-import-supports/expected/main.css, test/cases/at-import-supports/import-with-supports.css, test/cases/at-import-supports/index.js, test/cases/at-import-supports/style.css, test/cases/at-import-supports/test.css, test/cases/at-import-supports/webpack.config.js
add support for `supports()` and `layer()` in `@import`
No
No
=> feat: added supports for `supports()` and `layer()` in `@import`

src/plugin-options.json, test/__snapshots__/validate-plugin-options.test.js.snap, test/validate-plugin-options.test.js
Fix https://github.com/webpack-contrib/mini-css-extract-plugin/issues/877
No
Do not allow absolute paths in filename schema, add min length of 1.
=> fix: validate absolute paths in filename

src/plugin-options.json, test/__snapshots__/validate-plugin-options.test.js.snap, test/validate-plugin-options.test.js
As per https://github.com/webpack-contrib/mini-css-extract-plugin/pull/878 file paths shouldn't be absolute, so update the schema for the rule
https://github.com/webpack-contrib/mini-css-extract-plugin/pull/878
no
=> fix: do not allow absolute path in chunkFilename

src/index.js
=> fix: Pass absolute module path to serializer registration

.eslintignore
ignore `types` for eslint..
None
No
=> chore: ignore `types` for eslint

README.md
fix runtime value
Fix https://github.com/webpack-contrib/mini-css-extract-plugin/pull/929
No
No
=> docs: fix runtime value

README.md
=> Update README.md to reflect css-modules

src/loader.js, src/utils.js, test/cases/custom-loader-with-functional-exports/app/index.js, test/cases/custom-loader-with-functional-exports/app/mockLoader.js, test/cases/custom-loader-with-functional-exports/app/style.css, test/cases/custom-loader-with-functional-exports/expected/main.css, test/cases/custom-loader-with-functional-exports/expected/main.js, test/cases/custom-loader-with-functional-exports/webpack.config.js, test/stringifyLocal.test.js
I came across an interesting case in which a custom (modified) css-loader exports functions (as named exports). The [current implementation](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/loader.js#L231) uses `JSON.stringify`, which causes export values of type function ​​to become `undefined`. This small improvement will make it possible to handle function exports.
No braking changes.
=> feat(loader): add functions support for locals

src/index.js
Very hard to tests due we need to found a timeframe when it was created when it was refreshed and checkrf on rebuild late
No
No
=> fix: don't invalidate cache after timeout refresh

src/index.js, test/cases/at-import-external-with-media/a.css, test/cases/at-import-external-with-media/b.css, test/cases/at-import-external-with-media/expected/main.css, test/cases/at-import-external-with-media/index.js, test/cases/at-import-external-with-media/webpack.config.js
fixes https://github.com/webpack-contrib/mini-css-extract-plugin/issues/1049
No
No
=> fix: adding media, supports and layer for external import
